
int bitNor(int, int);
int test_bitNor(int, int);
int tmax();
int test_tmax();
int isNotEqual(int, int);
int test_isNotEqual(int, int);
int replaceByte(int, int, int);
int test_replaceByte(int, int, int);
int leastBitPos(int);
int test_leastBitPos(int);
int oddBits();
int test_oddBits();
int rotateLeft(int, int);
int test_rotateLeft(int, int);
int rempwr2(int, int);
int test_rempwr2(int, int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int bitParity(int);
int test_bitParity(int);
int multFiveEighths(int);
int test_multFiveEighths(int);
int logicalNeg(int);
int test_logicalNeg(int);
unsigned float_neg(unsigned);
unsigned test_float_neg(unsigned);
unsigned float_i2f(int);
unsigned test_float_i2f(int);
unsigned float_twice(unsigned);
unsigned test_float_twice(unsigned);
